src/java/co/com/sigap/controlador/RegistroNotasController.java
package co.com.sigap.controlador;

import co.com.sigap.entidades.RegistroNotas;
import co.com.sigap.controlador.util.JsfUtil;
import co.com.sigap.controlador.util.JsfUtil.PersistAction;

import java.io.Serializable;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;

@Named("registroNotasController")
@SessionScoped
public class RegistroNotasController implements Serializable {

    @EJB
    private co.com.sigap.controlador.RegistroNotasFacade ejbFacade;
    private List<RegistroNotas> items = null;
    private RegistroNotas selected;

    public RegistroNotasController() {
    }

    public RegistroNotas getSelected() {
        return selected;
    }

    public void setSelected(RegistroNotas selected) {
        this.selected = selected;
    }

    protected void setEmbeddableKeys() {
        selected.getRegistroNotasPK().setIdentificacionEstudiante(selected.getEstudiante().getCedulaEstudiante());
        selected.getRegistroNotasPK().setCodigoAsignatura(selected.getAsignatura().getCodigoAsignatura());
    }

    protected void initializeEmbeddableKey() {
        selected.setRegistroNotasPK(new co.com.sigap.entidades.RegistroNotasPK());
    }

    private RegistroNotasFacade getFacade() {
        return ejbFacade;
    }

    public RegistroNotas prepareCreate() {
        selected = new RegistroNotas();
        initializeEmbeddableKey();
        return selected;
    }

    public void create() {
        persist(PersistAction.CREATE, ResourceBundle.getBundle("/Bundle").getString("RegistroNotasCreated"));
        if (!JsfUtil.isValidationFailed()) {
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public void update() {
        persist(PersistAction.UPDATE, ResourceBundle.getBundle("/Bundle").getString("RegistroNotasUpdated"));
    }

    public void destroy() {
        persist(PersistAction.DELETE, ResourceBundle.getBundle("/Bundle").getString("RegistroNotasDeleted"));
        if (!JsfUtil.isValidationFailed()) {
            selected = null; // Remove selection
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public List<RegistroNotas> getItems() {
        //if (items == null) {
          items = getFacade().findAll();
        //}
        return items;
    }

    private void persist(PersistAction persistAction, String successMessage) {
        if (selected != null) {
            setEmbeddableKeys();
            try {
                if (persistAction != PersistAction.DELETE) {
                    getFacade().edit(selected);
                } else {
                    getFacade().remove(selected);
                }
                JsfUtil.addSuccessMessage(successMessage);
            } catch (EJBException ex) {
                String msg = "";
                Throwable cause = ex.getCause();
                if (cause != null) {
                    msg = cause.getLocalizedMessage();
                }
                if (msg.length() > 0) {
                    JsfUtil.addErrorMessage(msg);
                } else {
                    JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
                }
            } catch (Exception ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            }
        }
    }

    public RegistroNotas getRegistroNotas(co.com.sigap.entidades.RegistroNotasPK id) {
        return getFacade().find(id);
    }

    public List<RegistroNotas> getItemsAvailableSelectMany() {
        return getFacade().findAll();
    }

    public List<RegistroNotas> getItemsAvailableSelectOne() {
        return getFacade().findAll();
    }

    @FacesConverter(forClass = RegistroNotas.class)
    public static class RegistroNotasControllerConverter implements Converter {

        private static final String SEPARATOR = "#";
        private static final String SEPARATOR_ESCAPED = "\\#";

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            RegistroNotasController controller = (RegistroNotasController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "registroNotasController");
            return controller.getRegistroNotas(getKey(value));
        }

        co.com.sigap.entidades.RegistroNotasPK getKey(String value) {
            co.com.sigap.entidades.RegistroNotasPK key;
            String values[] = value.split(SEPARATOR_ESCAPED);
            key = new co.com.sigap.entidades.RegistroNotasPK();
            key.setCodigoAsignatura(values[0]);
            key.setIdentificacionEstudiante(values[1]);
            return key;
        }

        String getStringKey(co.com.sigap.entidades.RegistroNotasPK value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value.getCodigoAsignatura());
            sb.append(SEPARATOR);
            sb.append(value.getIdentificacionEstudiante());
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof RegistroNotas) {
                RegistroNotas o = (RegistroNotas) object;
                return getStringKey(o.getRegistroNotasPK());
            } else {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "object {0} is of type {1}; expected type: {2}", new Object[]{object, object.getClass().getName(), RegistroNotas.class.getName()});
                return null;
            }
        }

    }

}

web/registroNotas/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="RegistroNotasCreateDlg" widgetVar="RegistroNotasCreateDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.CreateRegistroNotasTitle}">
            <h:form id="RegistroNotasCreateForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{registroNotasController.selected != null}">
                        <p:outputLabel for="asignatura" value="#{bundle.CreateRegistroNotasLabel_asignatura}" />
                        <p:selectOneMenu value="#{parametricasBean.estudianteSeleccionado}" id="asignatura" required="true" requiredMessage="#{bundle.EditRegistroNotasRequiredMessage_asignatura}">
                            <f:selectItems value="#{asignaturaController.itemsAvailableSelectOne}"
                                           var="asignaturaItem"
                                           itemValue="#{asignaturaItem.toString()}"/>
                            <p:ajax event="change" listener="#{parametricasBean.muestreCambioEstudiante()}"
                                    update=":growl" />
                        </p:selectOneMenu>
                        
                        <p:outputLabel for="estudiante" value="#{bundle.CreateRegistroNotasLabel_estudiante}" />
                        <p:selectOneMenu id="estudiante" value="#{registroNotasController.selected.estudiante}" required="true" requiredMessage="#{bundle.EditRegistroNotasRequiredMessage_estudiante}">
                            <f:selectItems value="#{parametricasBean.asignatura}"
                                           var="fila"
                                           itemValue="#{fila.cedulaEstudiante}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.CreateRegistroNotasLabel_notaUno}" for="notaUno" />
                        <p:inputText id="notaUno" value="#{registroNotasController.selected.notaUno}" title="#{bundle.CreateRegistroNotasTitle_notaUno}" required="true" requiredMessage="#{bundle.CreateRegistroNotasRequiredMessage_notaUno}"/>
                        <p:outputLabel value="#{bundle.CreateRegistroNotasLabel_notaDos}" for="notaDos" />
                        <p:inputText id="notaDos" value="#{registroNotasController.selected.notaDos}" title="#{bundle.CreateRegistroNotasTitle_notaDos}" required="true" requiredMessage="#{bundle.CreateRegistroNotasRequiredMessage_notaDos}"/>
                        <p:outputLabel value="#{bundle.CreateRegistroNotasLabel_notaTres}" for="notaTres" />
                        <p:inputText id="notaTres" value="#{registroNotasController.selected.notaTres}" title="#{bundle.CreateRegistroNotasTitle_notaTres}" required="true" requiredMessage="#{bundle.CreateRegistroNotasRequiredMessage_notaTres}"/>
                        <p:outputLabel value="#{bundle.CreateRegistroNotasLabel_notaCuatro}" for="notaCuatro" />
                        <p:inputText id="notaCuatro" value="#{registroNotasController.selected.notaCuatro}" title="#{bundle.CreateRegistroNotasTitle_notaCuatro}" required="true" requiredMessage="#{bundle.CreateRegistroNotasRequiredMessage_notaCuatro}"/>
                        <p:outputLabel value="#{bundle.CreateRegistroNotasLabel_notaQuinto}" for="notaQuinto" />
                        <p:inputText id="notaQuinto" value="#{registroNotasController.selected.notaQuinto}" title="#{bundle.CreateRegistroNotasTitle_notaQuinto}" required="true" requiredMessage="#{bundle.CreateRegistroNotasRequiredMessage_notaQuinto}"/>
                        
                    </p:panelGrid>
                    <p:commandButton actionListener="#{registroNotasController.create}" value="#{bundle.Save}" update="display,:RegistroNotasListForm:datalist,:growl" oncomplete="handleSubmit(args,'RegistroNotasCreateDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" immediate="true" onclick="RegistroNotasCreateDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

web/registroNotas/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="RegistroNotasEditDlg" widgetVar="RegistroNotasEditDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.EditRegistroNotasTitle}">
            <h:form id="RegistroNotasEditForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{registroNotasController.selected != null}">
                        <p:outputLabel value="#{bundle.EditRegistroNotasLabel_notaUno}" for="notaUno" />
                        <p:inputText id="notaUno" value="#{registroNotasController.selected.notaUno}" title="#{bundle.EditRegistroNotasTitle_notaUno}" required="true" requiredMessage="#{bundle.EditRegistroNotasRequiredMessage_notaUno}"/>
                        <p:outputLabel value="#{bundle.EditRegistroNotasLabel_notaDos}" for="notaDos" />
                        <p:inputText id="notaDos" value="#{registroNotasController.selected.notaDos}" title="#{bundle.EditRegistroNotasTitle_notaDos}" required="true" requiredMessage="#{bundle.EditRegistroNotasRequiredMessage_notaDos}"/>
                        <p:outputLabel value="#{bundle.EditRegistroNotasLabel_notaTres}" for="notaTres" />
                        <p:inputText id="notaTres" value="#{registroNotasController.selected.notaTres}" title="#{bundle.EditRegistroNotasTitle_notaTres}" required="true" requiredMessage="#{bundle.EditRegistroNotasRequiredMessage_notaTres}"/>
                        <p:outputLabel value="#{bundle.EditRegistroNotasLabel_notaCuatro}" for="notaCuatro" />
                        <p:inputText id="notaCuatro" value="#{registroNotasController.selected.notaCuatro}" title="#{bundle.EditRegistroNotasTitle_notaCuatro}" required="true" requiredMessage="#{bundle.EditRegistroNotasRequiredMessage_notaCuatro}"/>
                        <p:outputLabel value="#{bundle.EditRegistroNotasLabel_notaQuinto}" for="notaQuinto" />
                        <p:inputText id="notaQuinto" value="#{registroNotasController.selected.notaQuinto}" title="#{bundle.EditRegistroNotasTitle_notaQuinto}" required="true" requiredMessage="#{bundle.EditRegistroNotasRequiredMessage_notaQuinto}"/>
                        <p:outputLabel value="#{bundle.EditRegistroNotasLabel_asignatura}" for="asignatura" />
                        <p:selectOneMenu id="asignatura" value="#{registroNotasController.selected.asignatura}" required="true" requiredMessage="#{bundle.EditRegistroNotasRequiredMessage_asignatura}">
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{asignaturaController.itemsAvailableSelectOne}"
                                           var="asignaturaItem"
                                           itemValue="#{asignaturaItem.toString()}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.EditRegistroNotasLabel_estudiante}" for="estudiante" />
                        <p:selectOneMenu id="estudiante" value="#{registroNotasController.selected.estudiante}" required="true" requiredMessage="#{bundle.EditRegistroNotasRequiredMessage_estudiante}">
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{estudianteController.itemsAvailableSelectOne}"
                                           var="estudianteItem"
                                           itemValue="#{estudianteItem.toString()}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{registroNotasController.update}" value="#{bundle.Save}" update="display,:RegistroNotasListForm:datalist,:growl" oncomplete="handleSubmit(args, 'RegistroNotasEditDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" immediate="true" onclick="RegistroNotasEditDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

web/registroNotas/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">


        <ui:define name="title">
            <h:outputText value="#{bundle.ListRegistroNotasTitle}"></h:outputText>
        </ui:define>

        <ui:define name="body">
            <h:form id="RegistroNotasListForm">
                <p:panel header="#{bundle.ListRegistroNotasTitle}">
                    <p:dataTable id="datalist" value="#{registroNotasController.items}" var="item"
                                 selectionMode="single" selection="#{registroNotasController.selected}"
                                 paginator="true"
                                 rowKey="#{item.registroNotasPK}"
                                 rows="10"
                                 rowsPerPageTemplate="10,20,30,40,50"
                                 >

                        <p:ajax event="rowSelect"   update="createButton viewButton editButton deleteButton"/>
                        <p:ajax event="rowUnselect" update="createButton viewButton editButton deleteButton"/>

                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListRegistroNotasTitle_notaUno}"/>
                            </f:facet>
                            <h:outputText value="#{item.notaUno}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListRegistroNotasTitle_notaDos}"/>
                            </f:facet>
                            <h:outputText value="#{item.notaDos}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListRegistroNotasTitle_notaTres}"/>
                            </f:facet>
                            <h:outputText value="#{item.notaTres}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListRegistroNotasTitle_notaCuatro}"/>
                            </f:facet>
                            <h:outputText value="#{item.notaCuatro}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListRegistroNotasTitle_notaQuinto}"/>
                            </f:facet>
                            <h:outputText value="#{item.notaQuinto}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListRegistroNotasTitle_asignatura}"/>
                            </f:facet>
                            <h:outputText value="#{item.asignatura.toString()}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListRegistroNotasTitle_estudiante}"/>
                            </f:facet>
                            <h:outputText value="#{item.estudiante.toString()}"/>
                        </p:column>
                        <f:facet name="footer">
                            <p:commandButton id="createButton" icon="ui-icon-plus"   value="#{bundle.Create}" actionListener="#{registroNotasController.prepareCreate}" update=":RegistroNotasCreateForm" oncomplete="PF('RegistroNotasCreateDialog').show()"/>
                            <p:commandButton id="viewButton"   icon="ui-icon-search" value="#{bundle.View}" update=":RegistroNotasViewForm" oncomplete="PF('RegistroNotasViewDialog').show()" disabled="#{empty registroNotasController.selected}"/>
                            <p:commandButton id="editButton"   icon="ui-icon-pencil" value="#{bundle.Edit}" update=":RegistroNotasEditForm" oncomplete="PF('RegistroNotasEditDialog').show()" disabled="#{empty registroNotasController.selected}"/>
                            <p:commandButton id="deleteButton" icon="ui-icon-trash"  value="#{bundle.Delete}" actionListener="#{registroNotasController.destroy}" update=":growl,datalist" disabled="#{empty registroNotasController.selected}"/>
                        </f:facet>
                    </p:dataTable>
                </p:panel>
            </h:form>

            <ui:include src="Create.xhtml"/>
            <ui:include src="Edit.xhtml"/>
            <ui:include src="View.xhtml"/>
        </ui:define>
    </ui:composition>

</html>

web/registroNotas/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="RegistroNotasViewDlg" widgetVar="RegistroNotasViewDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.ViewRegistroNotasTitle}">
            <h:form id="RegistroNotasViewForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{registroNotasController.selected != null}">
                        <h:outputText value="#{bundle.ViewRegistroNotasLabel_notaUno}"/>
                        <h:outputText value="#{registroNotasController.selected.notaUno}" title="#{bundle.ViewRegistroNotasTitle_notaUno}"/>
                        <h:outputText value="#{bundle.ViewRegistroNotasLabel_notaDos}"/>
                        <h:outputText value="#{registroNotasController.selected.notaDos}" title="#{bundle.ViewRegistroNotasTitle_notaDos}"/>
                        <h:outputText value="#{bundle.ViewRegistroNotasLabel_notaTres}"/>
                        <h:outputText value="#{registroNotasController.selected.notaTres}" title="#{bundle.ViewRegistroNotasTitle_notaTres}"/>
                        <h:outputText value="#{bundle.ViewRegistroNotasLabel_notaCuatro}"/>
                        <h:outputText value="#{registroNotasController.selected.notaCuatro}" title="#{bundle.ViewRegistroNotasTitle_notaCuatro}"/>
                        <h:outputText value="#{bundle.ViewRegistroNotasLabel_notaQuinto}"/>
                        <h:outputText value="#{registroNotasController.selected.notaQuinto}" title="#{bundle.ViewRegistroNotasTitle_notaQuinto}"/>
                        <h:outputText value="#{bundle.ViewRegistroNotasLabel_asignatura}"/>
                        <h:outputText value="#{registroNotasController.selected.asignatura}" title="#{bundle.ViewRegistroNotasTitle_asignatura}"/>
                        <h:outputText value="#{bundle.ViewRegistroNotasLabel_estudiante}"/>
                        <h:outputText value="#{registroNotasController.selected.estudiante}" title="#{bundle.ViewRegistroNotasTitle_estudiante}"/>
                    </p:panelGrid>
                    <p:commandButton value="#{bundle.Close}" onclick="RegistroNotasViewDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>